// Repository configuration organized by tiers
export const REPOSITORIES = {
  TIER_1: [
    'https://github.com/f/awesome-chatgpt-prompts',
    'https://github.com/dair-ai/Prompt-Engineering-Guide',
    'https://github.com/promptslab/Awesome-Prompt-Engineering',
    'https://github.com/natnew/Awesome-Prompt-Engineering',
    'https://github.com/NirDiamant/Prompt_Engineering',
    'https://github.com/brexhq/prompt-engineering',
    'https://github.com/snwfdhmp/awesome-gpt-prompt-engineering'
  ],
  
  TIER_2: [
    'https://github.com/x1xhlol/system-prompts-and-models-of-ai-tools',
    'https://github.com/jujumilk3/leaked-system-prompts',
    'https://github.com/asgeirtj/system_prompts_leaks',
    'https://github.com/elder-plinius/L1B3RT4S',
    'https://github.com/elder-plinius/CL4R1T4S'
  ],
  
  TIER_3: [
    'https://github.com/anthropics/claude-code',
    'https://github.com/cline/cline',
    'https://github.com/RooVetGit/Roo-Code',
    'https://github.com/Aider-AI/aider',
    'https://github.com/continuedev/continue',
    'https://github.com/OpenDevin/OpenDevin',
    'https://github.com/All-Hands-AI/OpenHands',
    'https://github.com/stitionai/devika',
    'https://github.com/camel-ai/camel',
    'https://github.com/microsoft/autogen',
    'https://github.com/crewAIInc/crewAI',
    'https://github.com/langchain-ai/langgraph',
    'https://github.com/langchain-ai/langchain',
    'https://github.com/run-llama/llama_index',
    'https://github.com/microsoft/semantic-kernel'
  ],
  
  TIER_4: [
    'https://github.com/pnp/copilot-prompts',
    'https://github.com/microsoft/promptbase',
    'https://github.com/microsoft/ai-agents-for-beginners',
    'https://github.com/microsoft/generative-ai-for-beginners',
    'https://github.com/microsoft/AI-For-Beginners',
    'https://github.com/microsoft/ML-For-Beginners'
  ],
  
  TIER_5: [
    'https://github.com/GoogleCloudPlatform/generative-ai',
    'https://github.com/google-gemini/cookbook',
    'https://github.com/google-gemini/generative-ai-docs'
  ],
  
  TIER_6: [
    'https://github.com/openai/openai-cookbook',
    'https://github.com/openai/openai-agents-python',
    'https://github.com/openai/evals',
    'https://github.com/openai/swarm'
  ],
  
  TIER_7: [
    'https://github.com/microsoft/autogen',
    'https://github.com/crewAIInc/crewAI',
    'https://github.com/langchain-ai/langgraph',
    'https://github.com/langchain-ai/langchain',
    'https://github.com/run-llama/llama_index',
    'https://github.com/OpenBMB/AgentVerse',
    'https://github.com/camel-ai/camel',
    'https://github.com/e2b-dev/awesome-ai-agents'
  ],
  
  TIER_8: [
    'https://github.com/langchain-ai/langchain',
    'https://github.com/run-llama/llama_index',
    'https://github.com/deepset-ai/haystack',
    'https://github.com/chroma-core/chroma',
    'https://github.com/weaviate/weaviate',
    'https://github.com/milvus-io/milvus',
    'https://github.com/qdrant/qdrant'
  ],
  
  TIER_9: [
    'https://github.com/Midgard-Research/Midjourney-Prompts',
    'https://github.com/lllyasviel/Fooocus',
    'https://github.com/comfyanonymous/ComfyUI',
    'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    'https://github.com/invoke-ai/InvokeAI'
  ],
  
  TIER_10: [
    'https://github.com/bigscience-workshop/promptsource',
    'https://github.com/bigscience-workshop/P3',
    'https://github.com/LAION-AI/Open-Assistant',
    'https://github.com/lm-sys/FastChat',
    'https://github.com/HuggingFaceH4/ultrachat',
    'https://github.com/HuggingFaceH4/ultrafeedback',
    'https://github.com/tatsu-lab/stanford_alpaca',
    'https://github.com/lm-sys/WildChat'
  ],
  
  TIER_11: [
    'https://github.com/domeccleston/sharegpt',
    'https://github.com/lm-sys/FastChat',
    'https://github.com/LAION-AI/Open-Assistant'
  ],
  
  TIER_12: [
    'https://github.com/openai/evals',
    'https://github.com/EleutherAI/lm-evaluation-harness',
    'https://github.com/huggingface/lighteval'
  ],
  
  TIER_13: [
    'https://github.com/microsoft/promptflow',
    'https://github.com/stanfordnlp/dspy',
    'https://github.com/guidance-ai/guidance',
    'https://github.com/outlines-dev/outlines'
  ],
  
  TIER_14: [
    'https://github.com/mahseema/awesome-ai-tools',
    'https://github.com/josephmisiti/awesome-machine-learning',
    'https://github.com/yzfly/Awesome-LLM',
    'https://github.com/Hannibal046/Awesome-LLM',
    'https://github.com/Shubhamsaboo/awesome-llm-apps'
  ],
  
  TIER_15: [
    'https://github.com/mckaywrigley/chatbot-ui',
    'https://github.com/ChatGPTNextWeb/NextChat',
    'https://github.com/lobehub/lobe-chat',
    'https://github.com/vercel/ai-chatbot'
  ],
  
  TIER_16: [
    'https://github.com/modelcontextprotocol/specification',
    'https://github.com/modelcontextprotocol/servers',
    'https://github.com/punkpeye/awesome-mcp-servers'
  ],
  
  TIER_17: [
    'https://github.com/tldrsec/prompt-injection-defenses',
    'https://github.com/protectai/rebuff',
    'https://github.com/NVIDIA/garak'
  ],
  
  TIER_18: [], // Role prompts - these are categories, not repos
  TIER_19: [], // Categories - these are categories, not repos
  TIER_20: []  // Hugging Face datasets - these are dataset searches, not repos
};

// Get all repositories as a flat array
export function getAllRepositories() {
  const allRepos = [];
  Object.values(REPOSITORIES).forEach(tier => {
    allRepos.push(...tier);
  });
  return [...new Set(allRepos)]; // Remove duplicates
}

// Search terms for discovering more repositories
export const SEARCH_TERMS = [
  'awesome-chatgpt-prompts',
  'awesome prompts',
  'awesome ai prompts',
  'awesome prompt engineering',
  'prompt engineering',
  'prompt library',
  'prompt collection',
  'prompt repository',
  'prompt template',
  'prompt templates',
  'prompt examples',
  'prompt dataset',
  'prompt datasets',
  'chatgpt prompts',
  'claude prompts',
  'gemini prompts',
  'gpt prompts',
  'llm prompts',
  'developer prompts',
  'coding prompts',
  'system prompts',
  'system prompt',
  'cursor prompts',
  'windsurf prompts',
  'cline prompts',
  'roo code prompts',
  'copilot prompts',
  'github copilot prompts',
  'ai prompts',
  'role prompts',
  'agent prompts',
  'rag prompts',
  'langchain prompts',
  'langgraph prompts',
  'crewai prompts',
  'autogen prompts',
  'semantic kernel prompts',
  'llamaindex prompts',
  'marketing prompts',
  'seo prompts',
  'sales prompts',
  'email prompts',
  'resume prompts',
  'interview prompts',
  'image prompts',
  'midjourney prompts',
  'stable diffusion prompts',
  'flux prompts',
  'sdxl prompts',
  'dalle prompts',
  'comfyui prompts',
  'software engineer prompts',
  'react prompts',
  'nextjs prompts',
  'nodejs prompts',
  'nestjs prompts',
  'python prompts',
  'java prompts',
  'csharp prompts',
  'dotnet prompts',
  'golang prompts',
  'rust prompts',
  'sql prompts',
  'mongodb prompts',
  'postgres prompts',
  'docker prompts',
  'kubernetes prompts',
  'aws prompts',
  'azure prompts',
  'gcp prompts',
  'linux prompts',
  'devops prompts',
  'ui ux prompts',
  'startup prompts',
  'business prompts',
  'finance prompts',
  'legal prompts',
  'medical prompts',
  'education prompts',
  'research prompts',
  'debug prompts',
  'review prompts',
  'documentation prompts',
  'architecture prompts',
  'function calling prompts',
  'tool calling prompts',
  'reasoning prompts',
  'cot prompts',
  'tree of thoughts',
  'react prompting',
  'few shot prompts',
  'zero shot prompts',
  'instruction dataset',
  'sharegpt',
  'ultrachat',
  'ultrafeedback',
  'alpaca dataset',
  'wildchat',
  'openassistant',
  'promptsource',
  'P3 prompts'
];

// Categories for classification
export const CATEGORIES = [
  'Programming',
  'Web Development',
  'Frontend',
  'Backend',
  'Full Stack',
  'React',
  'Next.js',
  'Angular',
  'Vue',
  'Node.js',
  'Express',
  'NestJS',
  'Python',
  'FastAPI',
  'Flask',
  'Django',
  'Java',
  'Spring Boot',
  'C#',
  '.NET',
  'Rust',
  'Go',
  'PHP',
  'Laravel',
  'SQL',
  'MongoDB',
  'PostgreSQL',
  'Redis',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'Linux',
  'Git',
  'GitHub',
  'CI/CD',
  'System Design',
  'DSA',
  'Competitive Programming',
  'Machine Learning',
  'Deep Learning',
  'LLMs',
  'Prompt Engineering',
  'RAG',
  'Agents',
  'MCP',
  'Automation',
  'n8n',
  'Power BI',
  'Excel',
  'PowerPoint',
  'Word',
  'Teams',
  'SQL Analytics',
  'Business',
  'Finance',
  'Marketing',
  'Sales',
  'SEO',
  'Resume',
  'Interview',
  'Email',
  'Social Media',
  'LinkedIn',
  'Startup',
  'Legal',
  'Medical',
  'Education',
  'Gaming',
  'Anime',
  'Story',
  'Poetry',
  'Translation',
  'Summarization',
  'Code Review',
  'Testing',
  'Documentation',
  'API Design',
  'Image Generation',
  'Midjourney',
  'Flux',
  'Stable Diffusion',
  'SDXL',
  'ComfyUI',
  'DALL·E'
];

// Role prompts categories
export const ROLE_CATEGORIES = [
  'Developer',
  'Software Engineer',
  'Architect',
  'CTO',
  'CEO',
  'Manager',
  'Teacher',
  'Professor',
  'Doctor',
  'Lawyer',
  'Financial Advisor',
  'Marketing Expert',
  'SEO Expert',
  'Content Writer',
  'Copywriter',
  'Translator',
  'Debugger',
  'Reviewer',
  'Data Scientist',
  'ML Engineer',
  'DevOps Engineer',
  'Cloud Engineer',
  'Cybersecurity Expert',
  'Business Analyst',
  'HR',
  'Recruiter',
  'Interviewer',
  'Product Manager',
  'UI UX Designer',
  'Prompt Engineer',
  'Researcher'
];

// File extensions to process
export const PROCESSABLE_EXTENSIONS = [
  '.md',
  '.markdown',
  '.txt',
  '.json',
  '.yaml',
  '.yml',
  '.xml',
  '.csv',
  '.html',
  '.htm',
  '.mdx'
];

// File patterns to ignore
export const IGNORE_PATTERNS = [
  'node_modules',
  '.git',
  'dist',
  'build',
  'target',
  'bin',
  'obj',
  '.vscode',
  '.idea',
  'coverage',
  '.next',
  '.nuxt',
  'vendor',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'composer.lock',
  'Gemfile.lock',
  '*.min.js',
  '*.min.css',
  '*.map',
  '*.png',
  '*.jpg',
  '*.jpeg',
  '*.gif',
  '*.svg',
  '*.ico',
  '*.pdf',
  '*.zip',
  '*.tar',
  '*.gz',
  '*.exe',
  '*.dll',
  '*.so',
  '*.dylib',
  'LICENSE',
  'LICENSE.md',
  'LICENSE.txt',
  'COPYING',
  'COPYRIGHT',
  'NOTICE',
  'AUTHORS',
  'CONTRIBUTORS',
  'CHANGES',
  'CHANGELOG',
  'HISTORY',
  'README.md',
  'README.txt',
  'README.rst',
  'CONTRIBUTING.md',
  'CODE_OF_CONDUCT.md',
  'SECURITY.md',
  '.gitignore',
  '.gitattributes',
  '.dockerignore',
  '.env',
  '.env.example',
  '.env.local',
  '.env.development',
  '.env.production',
  'Dockerfile',
  'docker-compose.yml',
  'docker-compose.yaml',
  'Makefile',
  'CMakeLists.txt',
  'setup.py',
  'setup.cfg',
  'pyproject.toml',
  'requirements.txt',
  'requirements-dev.txt',
  'Pipfile',
  'Pipfile.lock',
  'poetry.lock',
  'package.json',
  'tsconfig.json',
  '.eslintrc',
  '.eslintrc.js',
  '.eslintrc.json',
  '.prettierrc',
  '.prettierrc.js',
  '.prettierrc.json',
  '.babelrc',
  '.babelrc.js',
  '.babelrc.json',
  'jest.config.js',
  'jest.config.json',
  'vitest.config.js',
  'vitest.config.ts',
  'webpack.config.js',
  'webpack.config.ts',
  'rollup.config.js',
  'rollup.config.ts',
  'vite.config.js',
  'vite.config.ts',
  'next.config.js',
  'next.config.ts',
  'nuxt.config.js',
  'nuxt.config.ts',
  'vue.config.js'
];
